"""Generate the four SPA3 signal-PDU config files from SDB sources.

Inputs (both inside the GPA SDB complete ZIP):
  - SystemExtract ARXML  (ECU/*SystemExtract*.arxml)
  - Ethernet Backbone CSV (Reports/CNTimeCheckReport/*EthernetBackbone*.csv)

Outputs (consumed by spa2_decoder.pdu.load_config):
  - Signal_PDU_identifiers_ETH
  - Signal_PDU_Binding_PDU_Transport_ETH
  - Signal_PDU_signal_list_ETH
  - decode_as_entries

Signal layout logic mirrors the reference Cursed_PDU_Extractor. UDP PDU-Transport
ports are derived from the ARXML socket model (SOCKET-ADDRESS UDP port linked to
each signal PDU via SO-CON-I-PDU-IDENTIFIER / PDU-TRIGGERING), so all four files
are produced from the SDB with no hand-maintained Wireshark export.
"""

from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass, field
from pathlib import Path
from xml.etree import ElementTree as ET


NS = "{http://autosar.org/schema/r4.0}"
OUTPUT_FILES = ("Signal_PDU_identifiers_ETH", "Signal_PDU_Binding_PDU_Transport_ETH",
                "Signal_PDU_signal_list_ETH", "decode_as_entries")
_HEADER = "# This file is automatically generated, DO NOT MODIFY."


def _tag(name: str) -> str:
    return NS + name


def _last(ref: str | None) -> str:
    return ref.split("/")[-1] if ref else ""


def _format_number(value: float) -> str:
    if value == round(value) and abs(value) < 1e12:
        return str(int(round(value)))
    return f"{value:.10g}"


@dataclass
class ArxmlModel:
    base_types: dict = field(default_factory=dict)
    compu_methods: dict = field(default_factory=dict)
    isignals: dict = field(default_factory=dict)
    ipdus: dict = field(default_factory=dict)
    trigger_to_pdu: dict = field(default_factory=dict)
    socon_to_trigger: dict = field(default_factory=dict)
    sockets: list = field(default_factory=list)


def _signal_sort_key(mapping):
    start = mapping["start_pos"]
    if mapping["is_big_endian"]:
        return (start // 8, -(start % 8))
    return (start // 8, start % 8)


def parse_arxml(path: str | Path) -> ArxmlModel:
    """Single streaming pass over the (large) SystemExtract ARXML."""
    model = ArxmlModel()
    for _, elem in ET.iterparse(str(path), events=("end",)):
        tag = elem.tag
        if tag == _tag("SW-BASE-TYPE"):
            name = elem.findtext(_tag("SHORT-NAME")) or ""
            model.base_types[name] = {
                "size": int(elem.findtext(_tag("BASE-TYPE-SIZE")) or "0"),
                "is_signed": (elem.findtext(_tag("BASE-TYPE-ENCODING")) or "") == "2C"}
            elem.clear()
        elif tag == _tag("COMPU-METHOD"):
            name = elem.findtext(_tag("SHORT-NAME")) or ""
            if (elem.findtext(_tag("CATEGORY")) or "") == "LINEAR":
                nums = [float(v.text) for v in
                        elem.findall(".//" + _tag("COMPU-NUMERATOR") + "/" + _tag("V"))]
                dens = [float(v.text) for v in
                        elem.findall(".//" + _tag("COMPU-DENOMINATOR") + "/" + _tag("V"))]
                denom = dens[0] if dens else 1.0
                model.compu_methods[name] = {
                    "offset": nums[0] / denom if nums else 0.0,
                    "factor": nums[1] / denom if len(nums) >= 2 else 1.0}
            else:
                model.compu_methods[name] = {"factor": 1.0, "offset": 0.0}
            elem.clear()
        elif tag == _tag("I-SIGNAL"):
            name = elem.findtext(_tag("SHORT-NAME")) or ""
            conditional = elem.find(".//" + _tag("SW-DATA-DEF-PROPS-CONDITIONAL"))
            base = compu = ""
            if conditional is not None:
                base = _last(conditional.findtext(_tag("BASE-TYPE-REF")))
                compu = _last(conditional.findtext(_tag("COMPU-METHOD-REF")))
            model.isignals[name] = {
                "length_bits": int(elem.findtext(_tag("LENGTH")) or "0"),
                "base_type_name": base, "compu_method_name": compu}
            elem.clear()
        elif tag == _tag("I-SIGNAL-I-PDU"):
            _parse_ipdu(elem, model)
            elem.clear()
        elif tag == _tag("PDU-TRIGGERING"):
            name = elem.findtext(_tag("SHORT-NAME")) or ""
            model.trigger_to_pdu[name] = _last(elem.findtext(_tag("I-PDU-REF")))
            elem.clear()
        elif tag == _tag("SOCKET-CONNECTION-IPDU-IDENTIFIER-SET"):
            set_name = elem.findtext(_tag("SHORT-NAME")) or ""
            for ident in elem.findall(".//" + _tag("SO-CON-I-PDU-IDENTIFIER")):
                id_name = ident.findtext(_tag("SHORT-NAME"))
                trigger = _last(ident.findtext(_tag("PDU-TRIGGERING-REF")))
                if id_name and trigger:
                    model.socon_to_trigger[(set_name, id_name)] = trigger
            elem.clear()
        elif tag == _tag("SOCKET-ADDRESS"):
            _parse_socket_address(elem, model)
            elem.clear()
    return model


def _parse_socket_address(elem, model: ArxmlModel) -> None:
    udp = elem.find(".//" + _tag("UDP-TP"))
    if udp is None:
        return
    port_node = udp.find(".//" + _tag("PORT-NUMBER"))
    if port_node is None or not (port_node.text or "").strip().isdigit():
        return
    keys = []
    for ref in elem.iter(_tag("SO-CON-I-PDU-IDENTIFIER-REF")):
        parts = (ref.text or "").strip().split("/")
        if len(parts) >= 2:
            keys.append((parts[-2], parts[-1]))
    if keys:
        model.sockets.append((int(port_node.text), keys))


def _parse_ipdu(elem, model: ArxmlModel) -> None:
    name = elem.findtext(_tag("SHORT-NAME")) or ""
    mappings = []
    for mapping in elem.findall(".//" + _tag("I-SIGNAL-TO-I-PDU-MAPPING")):
        isignal_ref = mapping.findtext(_tag("I-SIGNAL-REF")) or ""
        if not isignal_ref:
            continue
        raw = mapping.findtext(_tag("SHORT-NAME")) or ""
        sig_name = re.sub(r"_[A-Za-z][A-Za-z0-9]*IPdu[0-9]+(?=_(?:mrx|mtx)$)", "", raw)
        sig_name = re.sub(r"_(?:mrx|mtx)$", "", sig_name)
        order = mapping.findtext(_tag("PACKING-BYTE-ORDER")) or "MOST-SIGNIFICANT-BYTE-LAST"
        try:
            start = int(mapping.findtext(_tag("START-POSITION")) or "0")
        except ValueError:
            start = 0
        mappings.append({"sig_name": sig_name, "isignal_name": _last(isignal_ref),
                         "is_big_endian": order == "MOST-SIGNIFICANT-BYTE-FIRST",
                         "start_pos": start})
    mappings.sort(key=_signal_sort_key)
    model.ipdus[name] = {"length_bytes": int(elem.findtext(_tag("LENGTH")) or "0"),
                         "mappings": mappings}


def read_backbone_csv(path: str | Path) -> list[tuple[str, str, str]]:
    rows = []
    with open(path, encoding="utf-8-sig") as source:
        reader = csv.reader(source)
        next(reader, None)
        for row in reader:
            if not row:
                continue
            identifier = row[1].strip() if len(row) > 1 else ""
            if identifier and all(c in "0123456789abcdefABCDEF" for c in identifier):
                rows.append((row[0].strip(), identifier.lower(),
                             row[2].strip() if len(row) > 2 else ""))
    return rows


def _signal_rows(model: ArxmlModel, pdu_idx_hex: str, pdu_name: str, length_bytes: int):
    lines = []
    cursor = 0
    sig_idx = 0
    for mapping in model.ipdus[pdu_name]["mappings"]:
        big_endian = mapping["is_big_endian"]
        start = mapping["start_pos"]
        effective = (start // 8) * 8 + (7 - start % 8) if big_endian else start
        signal = model.isignals.get(mapping["isignal_name"], {})
        length_bits = signal.get("length_bits", 0)
        endian = "TRUE" if big_endian else "FALSE"
        gap = effective - cursor
        if gap > 0:
            pad_base = min(64, max(8, ((gap + 7) // 8) * 8))
            lines.append(f'"{pdu_idx_hex}","{length_bytes}","{sig_idx}","__padding",'
                         f'"{pdu_name}.{pdu_name}.__padding","uint","{endian}",'
                         f'"{pad_base}","{gap}","1","0","FALSE","-1","TRUE"')
            sig_idx += 1
        base = model.base_types.get(signal.get("base_type_name", ""), {})
        dtype = "sint" if base.get("is_signed", False) else "uint"
        base_bits = min(64, max(8, ((length_bits + 7) // 8) * 8))
        compu = model.compu_methods.get(signal.get("compu_method_name", ""), {})
        factor = _format_number(compu.get("factor", 1.0))
        offset = _format_number(compu.get("offset", 0.0))
        lines.append(f'"{pdu_idx_hex}","{length_bytes}","{sig_idx}","{mapping["sig_name"]}",'
                     f'"{pdu_name}.{pdu_name}.{mapping["sig_name"]}","{dtype}","{endian}",'
                     f'"{base_bits}","{length_bits}","{factor}","{offset}","FALSE","-1","FALSE"')
        sig_idx += 1
        cursor = effective + length_bits
    return lines


def _derive_ports(model: ArxmlModel, pdu_names: set[str]) -> set[int]:
    ports = set()
    for port, keys in model.sockets:
        for key in keys:
            trigger = model.socon_to_trigger.get(key)
            if trigger and model.trigger_to_pdu.get(trigger) in pdu_names:
                ports.add(port)
                break
    return ports


def generate(arxml: str | Path, backbone_csv: str | Path, out_dir: str | Path) -> dict:
    model = parse_arxml(arxml)
    rows = read_backbone_csv(backbone_csv)

    identifiers = [_HEADER]
    bindings = [_HEADER]
    signals = [_HEADER]
    seen: dict[str, str] = {}
    matched_names: set[str] = set()
    index = 1
    for pdu_name, hex_id, lbit in rows:
        if pdu_name not in model.ipdus or hex_id in seen:
            continue
        length_bytes = model.ipdus[pdu_name]["length_bytes"]
        if length_bytes == 0 and lbit.isdigit():
            length_bytes = int(lbit) // 8
        idx_hex = format(index, "x")
        seen[hex_id] = idx_hex
        matched_names.add(pdu_name)
        bindings.append(f'"{hex_id}","{idx_hex}"')
        identifiers.append(f'"{idx_hex}","{pdu_name}.{pdu_name}"')
        signals.extend(_signal_rows(model, idx_hex, pdu_name, length_bytes))
        index += 1

    if len(bindings) <= 1:
        raise ValueError("No PDUs matched between the backbone CSV and the ARXML.")
    ports = _derive_ports(model, matched_names)
    if not ports:
        raise ValueError("No UDP PDU-Transport ports were derived from the ARXML "
                         "socket model; the socket schema may differ for this SDB.")

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    decode_as = ['# "Decode As" entries file, generated from the SDB ARXML socket model.']
    decode_as += [f"decode_as_entry: udp.port,{port},(none),PDU Transport"
                  for port in sorted(ports)]
    for name, lines in (("Signal_PDU_identifiers_ETH", identifiers),
                        ("Signal_PDU_Binding_PDU_Transport_ETH", bindings),
                        ("Signal_PDU_signal_list_ETH", signals),
                        ("decode_as_entries", decode_as)):
        (out_dir / name).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return {"pdus": len(bindings) - 1, "signals": len(signals) - 1, "ports": len(ports),
            "out_dir": str(out_dir)}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="generate_pdu_config", description=__doc__)
    parser.add_argument("--arxml", required=True, help="SystemExtract ARXML path")
    parser.add_argument("--csv", required=True, help="Ethernet Backbone CSV path")
    parser.add_argument("-o", "--out-dir", required=True, help="output directory")
    args = parser.parse_args(argv)
    result = generate(args.arxml, args.csv, args.out_dir)
    print(f"PDUs: {result['pdus']}  signals: {result['signals']}  "
          f"ports: {result['ports']}  -> {result['out_dir']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
