# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_resources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_resources.proto\"\xa2\x01\n\"ExteriorAudioResourcesCheckStarted\x12\x44\n\rresponse_code\x18\x01 \x01(\x0e\x32-.ExteriorAudioResourcesCheckStarted.ERespCode\"6\n\tERespCode\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\"\x8a\x01\n\x1c\x45xteriorAudioResourcesStatus\x12=\n\x0espeaker_status\x18\x01 \x01(\x0e\x32%.ExteriorAudioResourcesStatus.EStatus\"+\n\x07\x45Status\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x07\n\x03NOK\x10\x02\x62\x06proto3')



_EXTERIORAUDIORESOURCESCHECKSTARTED = DESCRIPTOR.message_types_by_name['ExteriorAudioResourcesCheckStarted']
_EXTERIORAUDIORESOURCESSTATUS = DESCRIPTOR.message_types_by_name['ExteriorAudioResourcesStatus']
_EXTERIORAUDIORESOURCESCHECKSTARTED_ERESPCODE = _EXTERIORAUDIORESOURCESCHECKSTARTED.enum_types_by_name['ERespCode']
_EXTERIORAUDIORESOURCESSTATUS_ESTATUS = _EXTERIORAUDIORESOURCESSTATUS.enum_types_by_name['EStatus']
ExteriorAudioResourcesCheckStarted = _reflection.GeneratedProtocolMessageType('ExteriorAudioResourcesCheckStarted', (_message.Message,), {
  'DESCRIPTOR' : _EXTERIORAUDIORESOURCESCHECKSTARTED,
  '__module__' : 'audio_resources_pb2'
  # @@protoc_insertion_point(class_scope:ExteriorAudioResourcesCheckStarted)
  })
_sym_db.RegisterMessage(ExteriorAudioResourcesCheckStarted)

ExteriorAudioResourcesStatus = _reflection.GeneratedProtocolMessageType('ExteriorAudioResourcesStatus', (_message.Message,), {
  'DESCRIPTOR' : _EXTERIORAUDIORESOURCESSTATUS,
  '__module__' : 'audio_resources_pb2'
  # @@protoc_insertion_point(class_scope:ExteriorAudioResourcesStatus)
  })
_sym_db.RegisterMessage(ExteriorAudioResourcesStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTERIORAUDIORESOURCESCHECKSTARTED._serialized_start=26
  _EXTERIORAUDIORESOURCESCHECKSTARTED._serialized_end=188
  _EXTERIORAUDIORESOURCESCHECKSTARTED_ERESPCODE._serialized_start=134
  _EXTERIORAUDIORESOURCESCHECKSTARTED_ERESPCODE._serialized_end=188
  _EXTERIORAUDIORESOURCESSTATUS._serialized_start=191
  _EXTERIORAUDIORESOURCESSTATUS._serialized_end=329
  _EXTERIORAUDIORESOURCESSTATUS_ESTATUS._serialized_start=286
  _EXTERIORAUDIORESOURCESSTATUS_ESTATUS._serialized_end=329
# @@protoc_insertion_point(module_scope)
