# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61udio_data.proto\x1a\x0cnanopb.proto\"\'\n\x0cHvacFanSpeed\x12\x17\n\x0f\x66\x61n_speed_value\x18\x01 \x01(\r\"\xcf\x01\n\x10\x45lectricalHealth\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.ElectricalHealth.Status\"\x90\x01\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12STATUS_NOT_LIMITED\x10\x01\x12\x1e\n\x1aSTATUS_REDUCED_PERFORMANCE\x10\x02\x12\x13\n\x0fSTATUS_DEGRADED\x10\x03\x12!\n\x1dSTATUS_LIMITED_POWER_CRITICAL\x10\x04\x62\x06proto3')



_HVACFANSPEED = DESCRIPTOR.message_types_by_name['HvacFanSpeed']
_ELECTRICALHEALTH = DESCRIPTOR.message_types_by_name['ElectricalHealth']
_ELECTRICALHEALTH_STATUS = _ELECTRICALHEALTH.enum_types_by_name['Status']
HvacFanSpeed = _reflection.GeneratedProtocolMessageType('HvacFanSpeed', (_message.Message,), {
  'DESCRIPTOR' : _HVACFANSPEED,
  '__module__' : 'audio_data_pb2'
  # @@protoc_insertion_point(class_scope:HvacFanSpeed)
  })
_sym_db.RegisterMessage(HvacFanSpeed)

ElectricalHealth = _reflection.GeneratedProtocolMessageType('ElectricalHealth', (_message.Message,), {
  'DESCRIPTOR' : _ELECTRICALHEALTH,
  '__module__' : 'audio_data_pb2'
  # @@protoc_insertion_point(class_scope:ElectricalHealth)
  })
_sym_db.RegisterMessage(ElectricalHealth)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HVACFANSPEED._serialized_start=34
  _HVACFANSPEED._serialized_end=73
  _ELECTRICALHEALTH._serialized_start=76
  _ELECTRICALHEALTH._serialized_end=283
  _ELECTRICALHEALTH_STATUS._serialized_start=139
  _ELECTRICALHEALTH_STATUS._serialized_end=283
# @@protoc_insertion_point(module_scope)
