# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: carconfig_adapter_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import signals_base_pb2 as signals__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63\x61rconfig_adapter_service.proto\x12\x05\x65\x43\x61ll\x1a\x0cnanopb.proto\x1a\x12signals_base.proto\":\n\x17ReadCarConfigParameters\x12\x1f\n\ndata_param\x18\x01 \x01(\x0c\x42\x0b\x92?\x03\x08\x96\x01\x92?\x02x\x01\"C\n\x1bReadCarConfigParametersResp\x12$\n\x0f\x64\x61ta_param_resp\x18\x01 \x01(\x0c\x42\x0b\x92?\x03\x08\xc8\x01\x92?\x02x\x01\"D\n$ReadVehicleIdentificationInformation\x12\x1c\n\x08\x64\x61ta_vid\x18\x01 \x01(\x0c\x42\n\x92?\x02\x08\n\x92?\x02x\x01\"M\n(ReadVehicleIdentificationInformationResp\x12!\n\rdata_vid_resp\x18\x01 \x01(\x0c\x42\n\x92?\x02\x08\x19\x92?\x02x\x01\x62\x06proto3')



_READCARCONFIGPARAMETERS = DESCRIPTOR.message_types_by_name['ReadCarConfigParameters']
_READCARCONFIGPARAMETERSRESP = DESCRIPTOR.message_types_by_name['ReadCarConfigParametersResp']
_READVEHICLEIDENTIFICATIONINFORMATION = DESCRIPTOR.message_types_by_name['ReadVehicleIdentificationInformation']
_READVEHICLEIDENTIFICATIONINFORMATIONRESP = DESCRIPTOR.message_types_by_name['ReadVehicleIdentificationInformationResp']
ReadCarConfigParameters = _reflection.GeneratedProtocolMessageType('ReadCarConfigParameters', (_message.Message,), {
  'DESCRIPTOR' : _READCARCONFIGPARAMETERS,
  '__module__' : 'carconfig_adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:eCall.ReadCarConfigParameters)
  })
_sym_db.RegisterMessage(ReadCarConfigParameters)

ReadCarConfigParametersResp = _reflection.GeneratedProtocolMessageType('ReadCarConfigParametersResp', (_message.Message,), {
  'DESCRIPTOR' : _READCARCONFIGPARAMETERSRESP,
  '__module__' : 'carconfig_adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:eCall.ReadCarConfigParametersResp)
  })
_sym_db.RegisterMessage(ReadCarConfigParametersResp)

ReadVehicleIdentificationInformation = _reflection.GeneratedProtocolMessageType('ReadVehicleIdentificationInformation', (_message.Message,), {
  'DESCRIPTOR' : _READVEHICLEIDENTIFICATIONINFORMATION,
  '__module__' : 'carconfig_adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:eCall.ReadVehicleIdentificationInformation)
  })
_sym_db.RegisterMessage(ReadVehicleIdentificationInformation)

ReadVehicleIdentificationInformationResp = _reflection.GeneratedProtocolMessageType('ReadVehicleIdentificationInformationResp', (_message.Message,), {
  'DESCRIPTOR' : _READVEHICLEIDENTIFICATIONINFORMATIONRESP,
  '__module__' : 'carconfig_adapter_service_pb2'
  # @@protoc_insertion_point(class_scope:eCall.ReadVehicleIdentificationInformationResp)
  })
_sym_db.RegisterMessage(ReadVehicleIdentificationInformationResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READCARCONFIGPARAMETERS.fields_by_name['data_param']._options = None
  _READCARCONFIGPARAMETERS.fields_by_name['data_param']._serialized_options = b'\222?\003\010\226\001\222?\002x\001'
  _READCARCONFIGPARAMETERSRESP.fields_by_name['data_param_resp']._options = None
  _READCARCONFIGPARAMETERSRESP.fields_by_name['data_param_resp']._serialized_options = b'\222?\003\010\310\001\222?\002x\001'
  _READVEHICLEIDENTIFICATIONINFORMATION.fields_by_name['data_vid']._options = None
  _READVEHICLEIDENTIFICATIONINFORMATION.fields_by_name['data_vid']._serialized_options = b'\222?\002\010\n\222?\002x\001'
  _READVEHICLEIDENTIFICATIONINFORMATIONRESP.fields_by_name['data_vid_resp']._options = None
  _READVEHICLEIDENTIFICATIONINFORMATIONRESP.fields_by_name['data_vid_resp']._serialized_options = b'\222?\002\010\031\222?\002x\001'
  _READCARCONFIGPARAMETERS._serialized_start=76
  _READCARCONFIGPARAMETERS._serialized_end=134
  _READCARCONFIGPARAMETERSRESP._serialized_start=136
  _READCARCONFIGPARAMETERSRESP._serialized_end=203
  _READVEHICLEIDENTIFICATIONINFORMATION._serialized_start=205
  _READVEHICLEIDENTIFICATIONINFORMATION._serialized_end=273
  _READVEHICLEIDENTIFICATIONINFORMATIONRESP._serialized_start=275
  _READVEHICLEIDENTIFICATIONINFORMATIONRESP._serialized_end=352
# @@protoc_insertion_point(module_scope)
