# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: certificate_provisioning_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&certificate_provisioning_service.proto\"N\n\x12\x43\x65rtificateRequest\x12\x1c\n\x03ver\x18\x01 \x01(\x0e\x32\x0f.PayloadVersion\x12\x0b\n\x03\x63sr\x18\x02 \x01(\x0c\x12\r\n\x05token\x18\x03 \x01(\t\"H\n\x13\x43\x65rtificateResponse\x12\x1c\n\x03ver\x18\x01 \x01(\x0e\x32\x0f.PayloadVersion\x12\x13\n\x0b\x63\x65rtificate\x18\x02 \x01(\x0c\"\x9c\x01\n\x19\x43\x65rtificateStatusResponse\x12\x1c\n\x03ver\x18\x01 \x01(\x0e\x32\x0f.PayloadVersion\x12*\n\x06status\x18\x02 \x01(\x0e\x32\x1a.CertificateResponseStatus\x12$\n\x10retry_not_before\x18\x03 \x01(\x0b\x32\n.Timestamp\x12\x0f\n\x07message\x18\x04 \x01(\t\"T\n\x14\x43\x65rtificateInstalled\x12\x1c\n\x03ver\x18\x01 \x01(\x0e\x32\x0f.PayloadVersion\x12\x1e\n\x16\x63\x65rtificateFingerprint\x18\x02 \x01(\x0c\"n\n\x1d\x43\x65rtificateInstallationFailed\x12\x1c\n\x03ver\x18\x01 \x01(\x0e\x32\x0f.PayloadVersion\x12\x1e\n\x16\x63\x65rtificateFingerprint\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05*g\n\x0ePayloadVersion\x12\x1f\n\x1bPAYLOAD_VERSION_UNKNOWN_VER\x10\x00\x12\x19\n\x15PAYLOAD_VERSION_VER_1\x10\x01\x12\x19\n\x15PAYLOAD_VERSION_VER_2\x10\x02*\xda\x01\n\x19\x43\x65rtificateResponseStatus\x12\"\n\x1eRESPONSE_STATUS_UNKNOWN_STATUS\x10\x00\x12\x1f\n\x1bRESPONSE_STATUS_IN_PROGRESS\x10\x01\x12\x1a\n\x16RESPONSE_STATUS_DENIED\x10\x02\x12\x1b\n\x17RESPONSE_STATUS_INVALID\x10\x03\x12#\n\x1fRESPONSE_STATUS_SERVICE_FAILURE\x10\x04\x12\x1a\n\x16RESPONSE_STATUS_REINIT\x10\x05\x62\x06proto3')

_PAYLOADVERSION = DESCRIPTOR.enum_types_by_name['PayloadVersion']
PayloadVersion = enum_type_wrapper.EnumTypeWrapper(_PAYLOADVERSION)
_CERTIFICATERESPONSESTATUS = DESCRIPTOR.enum_types_by_name['CertificateResponseStatus']
CertificateResponseStatus = enum_type_wrapper.EnumTypeWrapper(_CERTIFICATERESPONSESTATUS)
PAYLOAD_VERSION_UNKNOWN_VER = 0
PAYLOAD_VERSION_VER_1 = 1
PAYLOAD_VERSION_VER_2 = 2
RESPONSE_STATUS_UNKNOWN_STATUS = 0
RESPONSE_STATUS_IN_PROGRESS = 1
RESPONSE_STATUS_DENIED = 2
RESPONSE_STATUS_INVALID = 3
RESPONSE_STATUS_SERVICE_FAILURE = 4
RESPONSE_STATUS_REINIT = 5


_CERTIFICATEREQUEST = DESCRIPTOR.message_types_by_name['CertificateRequest']
_CERTIFICATERESPONSE = DESCRIPTOR.message_types_by_name['CertificateResponse']
_CERTIFICATESTATUSRESPONSE = DESCRIPTOR.message_types_by_name['CertificateStatusResponse']
_CERTIFICATEINSTALLED = DESCRIPTOR.message_types_by_name['CertificateInstalled']
_CERTIFICATEINSTALLATIONFAILED = DESCRIPTOR.message_types_by_name['CertificateInstallationFailed']
_TIMESTAMP = DESCRIPTOR.message_types_by_name['Timestamp']
CertificateRequest = _reflection.GeneratedProtocolMessageType('CertificateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEREQUEST,
  '__module__' : 'certificate_provisioning_service_pb2'
  # @@protoc_insertion_point(class_scope:CertificateRequest)
  })
_sym_db.RegisterMessage(CertificateRequest)

CertificateResponse = _reflection.GeneratedProtocolMessageType('CertificateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATERESPONSE,
  '__module__' : 'certificate_provisioning_service_pb2'
  # @@protoc_insertion_point(class_scope:CertificateResponse)
  })
_sym_db.RegisterMessage(CertificateResponse)

CertificateStatusResponse = _reflection.GeneratedProtocolMessageType('CertificateStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATESTATUSRESPONSE,
  '__module__' : 'certificate_provisioning_service_pb2'
  # @@protoc_insertion_point(class_scope:CertificateStatusResponse)
  })
_sym_db.RegisterMessage(CertificateStatusResponse)

CertificateInstalled = _reflection.GeneratedProtocolMessageType('CertificateInstalled', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEINSTALLED,
  '__module__' : 'certificate_provisioning_service_pb2'
  # @@protoc_insertion_point(class_scope:CertificateInstalled)
  })
_sym_db.RegisterMessage(CertificateInstalled)

CertificateInstallationFailed = _reflection.GeneratedProtocolMessageType('CertificateInstallationFailed', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATEINSTALLATIONFAILED,
  '__module__' : 'certificate_provisioning_service_pb2'
  # @@protoc_insertion_point(class_scope:CertificateInstallationFailed)
  })
_sym_db.RegisterMessage(CertificateInstallationFailed)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'certificate_provisioning_service_pb2'
  # @@protoc_insertion_point(class_scope:Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PAYLOADVERSION._serialized_start=598
  _PAYLOADVERSION._serialized_end=701
  _CERTIFICATERESPONSESTATUS._serialized_start=704
  _CERTIFICATERESPONSESTATUS._serialized_end=922
  _CERTIFICATEREQUEST._serialized_start=42
  _CERTIFICATEREQUEST._serialized_end=120
  _CERTIFICATERESPONSE._serialized_start=122
  _CERTIFICATERESPONSE._serialized_end=194
  _CERTIFICATESTATUSRESPONSE._serialized_start=197
  _CERTIFICATESTATUSRESPONSE._serialized_end=353
  _CERTIFICATEINSTALLED._serialized_start=355
  _CERTIFICATEINSTALLED._serialized_end=439
  _CERTIFICATEINSTALLATIONFAILED._serialized_start=441
  _CERTIFICATEINSTALLATIONFAILED._serialized_end=551
  _TIMESTAMP._serialized_start=553
  _TIMESTAMP._serialized_end=596
# @@protoc_insertion_point(module_scope)
