# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dhu_power_manager_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64hu_power_manager_service.proto\"7\n\x13RequestedPowerState\x12 \n\x0bpower_state\x18\x01 \x01(\x0e\x32\x0b.PowerState*&\n\nPowerState\x12\x07\n\x03Off\x10\x00\x12\x06\n\x02On\x10\x01\x12\x07\n\x03Str\x10\x02\x62\x06proto3')

_POWERSTATE = DESCRIPTOR.enum_types_by_name['PowerState']
PowerState = enum_type_wrapper.EnumTypeWrapper(_POWERSTATE)
Off = 0
On = 1
Str = 2


_REQUESTEDPOWERSTATE = DESCRIPTOR.message_types_by_name['RequestedPowerState']
RequestedPowerState = _reflection.GeneratedProtocolMessageType('RequestedPowerState', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTEDPOWERSTATE,
  '__module__' : 'dhu_power_manager_service_pb2'
  # @@protoc_insertion_point(class_scope:RequestedPowerState)
  })
_sym_db.RegisterMessage(RequestedPowerState)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POWERSTATE._serialized_start=92
  _POWERSTATE._serialized_end=130
  _REQUESTEDPOWERSTATE._serialized_start=35
  _REQUESTEDPOWERSTATE._serialized_end=90
# @@protoc_insertion_point(module_scope)
