# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: display_control_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64isplay_control_data.proto\x12\x04\x64ico\"\x9a\x02\n\x0f\x44isplaySettings\x12\x45\n\x13interior_brightness\x18\x01 \x01(\x0b\x32(.dico.DisplaySettings.InteriorBrightness\x12\x33\n\nnight_mode\x18\x02 \x01(\x0e\x32\x1f.dico.DisplaySettings.NightMode\x1a;\n\x12InteriorBrightness\x12\x0b\n\x03hud\x18\x01 \x01(\r\x12\x0b\n\x03\x64im\x18\x02 \x01(\r\x12\x0b\n\x03\x63sd\x18\x03 \x01(\r\"N\n\tNightMode\x12\x1a\n\x16NIGHT_MODE_UNSPECIFIED\x10\x00\x12\x11\n\rNIGHT_MODE_ON\x10\x01\x12\x12\n\x0eNIGHT_MODE_OFF\x10\x02\"\\\n\x15HudAdjustmentSettings\x12\x12\n\nbrightness\x18\x01 \x01(\r\x12\x17\n\x0fmirror_position\x18\x02 \x01(\r\x12\x16\n\x0eimage_rotation\x18\x03 \x01(\x05\x62\x06proto3')



_DISPLAYSETTINGS = DESCRIPTOR.message_types_by_name['DisplaySettings']
_DISPLAYSETTINGS_INTERIORBRIGHTNESS = _DISPLAYSETTINGS.nested_types_by_name['InteriorBrightness']
_HUDADJUSTMENTSETTINGS = DESCRIPTOR.message_types_by_name['HudAdjustmentSettings']
_DISPLAYSETTINGS_NIGHTMODE = _DISPLAYSETTINGS.enum_types_by_name['NightMode']
DisplaySettings = _reflection.GeneratedProtocolMessageType('DisplaySettings', (_message.Message,), {

  'InteriorBrightness' : _reflection.GeneratedProtocolMessageType('InteriorBrightness', (_message.Message,), {
    'DESCRIPTOR' : _DISPLAYSETTINGS_INTERIORBRIGHTNESS,
    '__module__' : 'display_control_data_pb2'
    # @@protoc_insertion_point(class_scope:dico.DisplaySettings.InteriorBrightness)
    })
  ,
  'DESCRIPTOR' : _DISPLAYSETTINGS,
  '__module__' : 'display_control_data_pb2'
  # @@protoc_insertion_point(class_scope:dico.DisplaySettings)
  })
_sym_db.RegisterMessage(DisplaySettings)
_sym_db.RegisterMessage(DisplaySettings.InteriorBrightness)

HudAdjustmentSettings = _reflection.GeneratedProtocolMessageType('HudAdjustmentSettings', (_message.Message,), {
  'DESCRIPTOR' : _HUDADJUSTMENTSETTINGS,
  '__module__' : 'display_control_data_pb2'
  # @@protoc_insertion_point(class_scope:dico.HudAdjustmentSettings)
  })
_sym_db.RegisterMessage(HudAdjustmentSettings)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISPLAYSETTINGS._serialized_start=37
  _DISPLAYSETTINGS._serialized_end=319
  _DISPLAYSETTINGS_INTERIORBRIGHTNESS._serialized_start=180
  _DISPLAYSETTINGS_INTERIORBRIGHTNESS._serialized_end=239
  _DISPLAYSETTINGS_NIGHTMODE._serialized_start=241
  _DISPLAYSETTINGS_NIGHTMODE._serialized_end=319
  _HUDADJUSTMENTSETTINGS._serialized_start=321
  _HUDADJUSTMENTSETTINGS._serialized_end=413
# @@protoc_insertion_point(module_scope)
