# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: long_horizon_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1along_horizon_service.proto\x1a\x0cnanopb.proto\"0\n\nSpeedDelta\x12\x13\n\x0b\x64ist_offset\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"4\n\x0e\x45levationDelta\x12\x13\n\x0b\x64ist_offset\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"J\n\x07Segment\x12\"\n\televation\x18\x01 \x01(\x0b\x32\x0f.ElevationDelta\x12\x1b\n\x06speeds\x18\x02 \x03(\x0b\x32\x0b.SpeedDelta\"S\n\x0bLongHorizon\x12\x10\n\x08route_id\x18\x01 \x01(\r\x12\x16\n\x0e\x64ist_travelled\x18\x02 \x01(\r\x12\x1a\n\x08segments\x18\x03 \x03(\x0b\x32\x08.Segment\"+\n\x10NavigationStatus\x12\x17\n\x0fhas_destination\x18\x01 \x01(\x08\"`\n\x11LongHorizonParcel\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x15\n\rtotal_parcels\x18\x02 \x01(\r\x12\x12\n\nparcel_num\x18\x03 \x01(\r\x12\x14\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x42\x06\x92?\x03\x08\xc6\nb\x06proto3')



_SPEEDDELTA = DESCRIPTOR.message_types_by_name['SpeedDelta']
_ELEVATIONDELTA = DESCRIPTOR.message_types_by_name['ElevationDelta']
_SEGMENT = DESCRIPTOR.message_types_by_name['Segment']
_LONGHORIZON = DESCRIPTOR.message_types_by_name['LongHorizon']
_NAVIGATIONSTATUS = DESCRIPTOR.message_types_by_name['NavigationStatus']
_LONGHORIZONPARCEL = DESCRIPTOR.message_types_by_name['LongHorizonParcel']
SpeedDelta = _reflection.GeneratedProtocolMessageType('SpeedDelta', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDDELTA,
  '__module__' : 'long_horizon_service_pb2'
  # @@protoc_insertion_point(class_scope:SpeedDelta)
  })
_sym_db.RegisterMessage(SpeedDelta)

ElevationDelta = _reflection.GeneratedProtocolMessageType('ElevationDelta', (_message.Message,), {
  'DESCRIPTOR' : _ELEVATIONDELTA,
  '__module__' : 'long_horizon_service_pb2'
  # @@protoc_insertion_point(class_scope:ElevationDelta)
  })
_sym_db.RegisterMessage(ElevationDelta)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'long_horizon_service_pb2'
  # @@protoc_insertion_point(class_scope:Segment)
  })
_sym_db.RegisterMessage(Segment)

LongHorizon = _reflection.GeneratedProtocolMessageType('LongHorizon', (_message.Message,), {
  'DESCRIPTOR' : _LONGHORIZON,
  '__module__' : 'long_horizon_service_pb2'
  # @@protoc_insertion_point(class_scope:LongHorizon)
  })
_sym_db.RegisterMessage(LongHorizon)

NavigationStatus = _reflection.GeneratedProtocolMessageType('NavigationStatus', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATIONSTATUS,
  '__module__' : 'long_horizon_service_pb2'
  # @@protoc_insertion_point(class_scope:NavigationStatus)
  })
_sym_db.RegisterMessage(NavigationStatus)

LongHorizonParcel = _reflection.GeneratedProtocolMessageType('LongHorizonParcel', (_message.Message,), {
  'DESCRIPTOR' : _LONGHORIZONPARCEL,
  '__module__' : 'long_horizon_service_pb2'
  # @@protoc_insertion_point(class_scope:LongHorizonParcel)
  })
_sym_db.RegisterMessage(LongHorizonParcel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LONGHORIZONPARCEL.fields_by_name['data']._options = None
  _LONGHORIZONPARCEL.fields_by_name['data']._serialized_options = b'\222?\003\010\306\n'
  _SPEEDDELTA._serialized_start=44
  _SPEEDDELTA._serialized_end=92
  _ELEVATIONDELTA._serialized_start=94
  _ELEVATIONDELTA._serialized_end=146
  _SEGMENT._serialized_start=148
  _SEGMENT._serialized_end=222
  _LONGHORIZON._serialized_start=224
  _LONGHORIZON._serialized_end=307
  _NAVIGATIONSTATUS._serialized_start=309
  _NAVIGATIONSTATUS._serialized_end=352
  _LONGHORIZONPARCEL._serialized_start=354
  _LONGHORIZONPARCEL._serialized_end=450
# @@protoc_insertion_point(module_scope)
