# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parking_climate_provider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eparking_climate_provider.proto\x12\x03pcp\x1a\x0cnanopb.proto\"\xc7\x01\n\x05Timer\x12\x15\n\rdepature_time\x18\x01 \x01(\r\x12\x13\n\x0btimer_state\x18\x02 \x01(\r\x12\x15\n\rrepeat_weekly\x18\x03 \x01(\x08\x12\r\n\x05\x64\x61y_1\x18\x04 \x01(\r\x12\r\n\x05\x64\x61y_2\x18\x05 \x01(\r\x12\r\n\x05\x64\x61y_3\x18\x06 \x01(\r\x12\r\n\x05\x64\x61y_4\x18\x07 \x01(\r\x12\r\n\x05\x64\x61y_5\x18\x08 \x01(\r\x12\r\n\x05\x64\x61y_6\x18\t \x01(\r\x12\r\n\x05\x64\x61y_7\x18\n \x01(\r\x12\x12\n\nsort_order\x18\x0b \x01(\r\"-\n\tTimerList\x12 \n\x05timer\x18\x01 \x03(\x0b\x32\n.pcp.TimerB\x05\x92?\x02\x10\x08\"\x83\x02\n\x11KeepClimateActive\x12\x11\n\tis_active\x18\x01 \x01(\x08\x12>\n\x0c\x61vailability\x18\x02 \x01(\x0e\x32#.pcp.KeepClimateActive.AvailabilityH\x00\x88\x01\x01\"\x89\x01\n\x0c\x41vailability\x12\x1c\n\x18\x41VAILABILITY_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x41VAILABILITY_AVAILABLE\x10\x01\x12!\n\x1d\x41VAILABILITY_TEMP_UNAVAILABLE\x10\x02\x12\x1c\n\x18\x41VAILABILITY_UNAVAILABLE\x10\x03\x42\x0f\n\r_availability\"\xe6\x01\n\x12\x43limateInformation\x12\x1d\n\x15run_time_left_warning\x18\x01 \x01(\x08\x12\x1c\n\x14reached_max_run_time\x18\x02 \x01(\x08\x12!\n\x19persistent_error_detected\x18\x03 \x01(\x08\x12\x19\n\x11\x61\x63tivated_low_soc\x18\x04 \x01(\x08\x12\x1e\n\x16\x61\x63tivated_critical_soc\x18\x05 \x01(\x08\x12\x17\n\x0freached_low_soc\x18\x06 \x01(\x08\x12\x1c\n\x14reached_critical_soc\x18\x07 \x01(\x08\x62\x06proto3')



_TIMER = DESCRIPTOR.message_types_by_name['Timer']
_TIMERLIST = DESCRIPTOR.message_types_by_name['TimerList']
_KEEPCLIMATEACTIVE = DESCRIPTOR.message_types_by_name['KeepClimateActive']
_CLIMATEINFORMATION = DESCRIPTOR.message_types_by_name['ClimateInformation']
_KEEPCLIMATEACTIVE_AVAILABILITY = _KEEPCLIMATEACTIVE.enum_types_by_name['Availability']
Timer = _reflection.GeneratedProtocolMessageType('Timer', (_message.Message,), {
  'DESCRIPTOR' : _TIMER,
  '__module__' : 'parking_climate_provider_pb2'
  # @@protoc_insertion_point(class_scope:pcp.Timer)
  })
_sym_db.RegisterMessage(Timer)

TimerList = _reflection.GeneratedProtocolMessageType('TimerList', (_message.Message,), {
  'DESCRIPTOR' : _TIMERLIST,
  '__module__' : 'parking_climate_provider_pb2'
  # @@protoc_insertion_point(class_scope:pcp.TimerList)
  })
_sym_db.RegisterMessage(TimerList)

KeepClimateActive = _reflection.GeneratedProtocolMessageType('KeepClimateActive', (_message.Message,), {
  'DESCRIPTOR' : _KEEPCLIMATEACTIVE,
  '__module__' : 'parking_climate_provider_pb2'
  # @@protoc_insertion_point(class_scope:pcp.KeepClimateActive)
  })
_sym_db.RegisterMessage(KeepClimateActive)

ClimateInformation = _reflection.GeneratedProtocolMessageType('ClimateInformation', (_message.Message,), {
  'DESCRIPTOR' : _CLIMATEINFORMATION,
  '__module__' : 'parking_climate_provider_pb2'
  # @@protoc_insertion_point(class_scope:pcp.ClimateInformation)
  })
_sym_db.RegisterMessage(ClimateInformation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMERLIST.fields_by_name['timer']._options = None
  _TIMERLIST.fields_by_name['timer']._serialized_options = b'\222?\002\020\010'
  _TIMER._serialized_start=54
  _TIMER._serialized_end=253
  _TIMERLIST._serialized_start=255
  _TIMERLIST._serialized_end=300
  _KEEPCLIMATEACTIVE._serialized_start=303
  _KEEPCLIMATEACTIVE._serialized_end=562
  _KEEPCLIMATEACTIVE_AVAILABILITY._serialized_start=408
  _KEEPCLIMATEACTIVE_AVAILABILITY._serialized_end=545
  _CLIMATEINFORMATION._serialized_start=565
  _CLIMATEINFORMATION._serialized_end=795
# @@protoc_insertion_point(module_scope)
