# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reset_manager_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1breset_manager_service.proto\x1a\x0cnanopb.proto\"M\n\x17\x46\x61\x63toryResetInfoMessage\x12\x19\n\x11timestamp_initial\x18\x01 \x01(\x04\x12\x17\n\x0ftimestamp_final\x18\x02 \x01(\x04\x62\x06proto3')



_FACTORYRESETINFOMESSAGE = DESCRIPTOR.message_types_by_name['FactoryResetInfoMessage']
FactoryResetInfoMessage = _reflection.GeneratedProtocolMessageType('FactoryResetInfoMessage', (_message.Message,), {
  'DESCRIPTOR' : _FACTORYRESETINFOMESSAGE,
  '__module__' : 'reset_manager_service_pb2'
  # @@protoc_insertion_point(class_scope:FactoryResetInfoMessage)
  })
_sym_db.RegisterMessage(FactoryResetInfoMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FACTORYRESETINFOMESSAGE._serialized_start=45
  _FACTORYRESETINFOMESSAGE._serialized_end=122
# @@protoc_insertion_point(module_scope)
