# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rva_pushoffloader_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1frva_pushoffloader_service.proto\"\x1d\n\nOriginList\x12\x0f\n\x07origins\x18\x01 \x03(\t\"2\n\x12OffloadDataRequest\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"4\n\x10OffloadDataReply\x12 \n\terror_msg\x18\x01 \x01(\x0e\x32\r.OffloadError*q\n\x0cOffloadError\x12\x0b\n\x07SUCCESS\x10\x00\x12\x16\n\x12ORIGIN_NOT_ALLOWED\x10\x01\x12\x12\n\x0ePARSING_FAILED\x10\x02\x12\x11\n\rUNKNOWN_ERROR\x10\x03\x12\x15\n\x11\x43ONTENT_TOO_LARGE\x10\x04\x32\xb9\x01\n\x14PushOffloaderService\x12\x33\n\x17\x46ilterOutAllowedOrigins\x12\x0b.OriginList\x1a\x0b.OriginList\x12\x35\n\x0bOffloadData\x12\x13.OffloadDataRequest\x1a\x11.OffloadDataReply\x12\x35\n\x19GetMatchingAllowedOrigins\x12\x0b.OriginList\x1a\x0b.OriginListb\x06proto3')

_OFFLOADERROR = DESCRIPTOR.enum_types_by_name['OffloadError']
OffloadError = enum_type_wrapper.EnumTypeWrapper(_OFFLOADERROR)
SUCCESS = 0
ORIGIN_NOT_ALLOWED = 1
PARSING_FAILED = 2
UNKNOWN_ERROR = 3
CONTENT_TOO_LARGE = 4


_ORIGINLIST = DESCRIPTOR.message_types_by_name['OriginList']
_OFFLOADDATAREQUEST = DESCRIPTOR.message_types_by_name['OffloadDataRequest']
_OFFLOADDATAREPLY = DESCRIPTOR.message_types_by_name['OffloadDataReply']
OriginList = _reflection.GeneratedProtocolMessageType('OriginList', (_message.Message,), {
  'DESCRIPTOR' : _ORIGINLIST,
  '__module__' : 'rva_pushoffloader_service_pb2'
  # @@protoc_insertion_point(class_scope:OriginList)
  })
_sym_db.RegisterMessage(OriginList)

OffloadDataRequest = _reflection.GeneratedProtocolMessageType('OffloadDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _OFFLOADDATAREQUEST,
  '__module__' : 'rva_pushoffloader_service_pb2'
  # @@protoc_insertion_point(class_scope:OffloadDataRequest)
  })
_sym_db.RegisterMessage(OffloadDataRequest)

OffloadDataReply = _reflection.GeneratedProtocolMessageType('OffloadDataReply', (_message.Message,), {
  'DESCRIPTOR' : _OFFLOADDATAREPLY,
  '__module__' : 'rva_pushoffloader_service_pb2'
  # @@protoc_insertion_point(class_scope:OffloadDataReply)
  })
_sym_db.RegisterMessage(OffloadDataReply)

_PUSHOFFLOADERSERVICE = DESCRIPTOR.services_by_name['PushOffloaderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OFFLOADERROR._serialized_start=172
  _OFFLOADERROR._serialized_end=285
  _ORIGINLIST._serialized_start=35
  _ORIGINLIST._serialized_end=64
  _OFFLOADDATAREQUEST._serialized_start=66
  _OFFLOADDATAREQUEST._serialized_end=116
  _OFFLOADDATAREPLY._serialized_start=118
  _OFFLOADDATAREPLY._serialized_end=170
  _PUSHOFFLOADERSERVICE._serialized_start=288
  _PUSHOFFLOADERSERVICE._serialized_end=473
# @@protoc_insertion_point(module_scope)
