# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scene_controller_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1escene_controller_service.proto\x12\x0fSceneController\x1a\x0cnanopb.proto\"C\n\x07SceneId\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1c\n\rfriendly_name\x18\x02 \x01(\tB\x05\x92?\x02\x08@\x12\x0e\n\x06subset\x18\x03 \x01(\r\"j\n\nEnterScene\x12\x12\n\nusage_mode\x18\x01 \x01(\r\x12\x1c\n\x08settings\x18\x02 \x03(\tB\n\x92?\x02\x08\x64\x92?\x02\x10\n\x12*\n\x08scene_id\x18\x03 \x01(\x0b\x32\x18.SceneController.SceneId\"7\n\tExitScene\x12*\n\x08scene_id\x18\x01 \x01(\x0b\x32\x18.SceneController.SceneId\"E\n\rSendHeartbeat\x12\x19\n\x11heartbeat_counter\x18\x01 \x01(\r\x12\x19\n\x11heartbeat_timeout\x18\x02 \x01(\r\"#\n\x12GetAllActiveScenes\x12\r\n\x05\x64ummy\x18\x01 \x01(\x08\" \n\x0e\x45nterSceneResp\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x1f\n\rExitSceneResp\x12\x0e\n\x06result\x18\x01 \x01(\x08\">\n\x11SendHeartbeatResp\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x19\n\x11heartbeat_counter\x18\x02 \x01(\r\"`\n\x16GetAllActiveScenesResp\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x36\n\ractive_scenes\x18\x02 \x03(\x0b\x32\x18.SceneController.SceneIdB\x05\x92?\x02\x10\x05\x62\x06proto3')



_SCENEID = DESCRIPTOR.message_types_by_name['SceneId']
_ENTERSCENE = DESCRIPTOR.message_types_by_name['EnterScene']
_EXITSCENE = DESCRIPTOR.message_types_by_name['ExitScene']
_SENDHEARTBEAT = DESCRIPTOR.message_types_by_name['SendHeartbeat']
_GETALLACTIVESCENES = DESCRIPTOR.message_types_by_name['GetAllActiveScenes']
_ENTERSCENERESP = DESCRIPTOR.message_types_by_name['EnterSceneResp']
_EXITSCENERESP = DESCRIPTOR.message_types_by_name['ExitSceneResp']
_SENDHEARTBEATRESP = DESCRIPTOR.message_types_by_name['SendHeartbeatResp']
_GETALLACTIVESCENESRESP = DESCRIPTOR.message_types_by_name['GetAllActiveScenesResp']
SceneId = _reflection.GeneratedProtocolMessageType('SceneId', (_message.Message,), {
  'DESCRIPTOR' : _SCENEID,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.SceneId)
  })
_sym_db.RegisterMessage(SceneId)

EnterScene = _reflection.GeneratedProtocolMessageType('EnterScene', (_message.Message,), {
  'DESCRIPTOR' : _ENTERSCENE,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.EnterScene)
  })
_sym_db.RegisterMessage(EnterScene)

ExitScene = _reflection.GeneratedProtocolMessageType('ExitScene', (_message.Message,), {
  'DESCRIPTOR' : _EXITSCENE,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.ExitScene)
  })
_sym_db.RegisterMessage(ExitScene)

SendHeartbeat = _reflection.GeneratedProtocolMessageType('SendHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _SENDHEARTBEAT,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.SendHeartbeat)
  })
_sym_db.RegisterMessage(SendHeartbeat)

GetAllActiveScenes = _reflection.GeneratedProtocolMessageType('GetAllActiveScenes', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTIVESCENES,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.GetAllActiveScenes)
  })
_sym_db.RegisterMessage(GetAllActiveScenes)

EnterSceneResp = _reflection.GeneratedProtocolMessageType('EnterSceneResp', (_message.Message,), {
  'DESCRIPTOR' : _ENTERSCENERESP,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.EnterSceneResp)
  })
_sym_db.RegisterMessage(EnterSceneResp)

ExitSceneResp = _reflection.GeneratedProtocolMessageType('ExitSceneResp', (_message.Message,), {
  'DESCRIPTOR' : _EXITSCENERESP,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.ExitSceneResp)
  })
_sym_db.RegisterMessage(ExitSceneResp)

SendHeartbeatResp = _reflection.GeneratedProtocolMessageType('SendHeartbeatResp', (_message.Message,), {
  'DESCRIPTOR' : _SENDHEARTBEATRESP,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.SendHeartbeatResp)
  })
_sym_db.RegisterMessage(SendHeartbeatResp)

GetAllActiveScenesResp = _reflection.GeneratedProtocolMessageType('GetAllActiveScenesResp', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTIVESCENESRESP,
  '__module__' : 'scene_controller_service_pb2'
  # @@protoc_insertion_point(class_scope:SceneController.GetAllActiveScenesResp)
  })
_sym_db.RegisterMessage(GetAllActiveScenesResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENEID.fields_by_name['friendly_name']._options = None
  _SCENEID.fields_by_name['friendly_name']._serialized_options = b'\222?\002\010@'
  _ENTERSCENE.fields_by_name['settings']._options = None
  _ENTERSCENE.fields_by_name['settings']._serialized_options = b'\222?\002\010d\222?\002\020\n'
  _GETALLACTIVESCENESRESP.fields_by_name['active_scenes']._options = None
  _GETALLACTIVESCENESRESP.fields_by_name['active_scenes']._serialized_options = b'\222?\002\020\005'
  _SCENEID._serialized_start=65
  _SCENEID._serialized_end=132
  _ENTERSCENE._serialized_start=134
  _ENTERSCENE._serialized_end=240
  _EXITSCENE._serialized_start=242
  _EXITSCENE._serialized_end=297
  _SENDHEARTBEAT._serialized_start=299
  _SENDHEARTBEAT._serialized_end=368
  _GETALLACTIVESCENES._serialized_start=370
  _GETALLACTIVESCENES._serialized_end=405
  _ENTERSCENERESP._serialized_start=407
  _ENTERSCENERESP._serialized_end=439
  _EXITSCENERESP._serialized_start=441
  _EXITSCENERESP._serialized_end=472
  _SENDHEARTBEATRESP._serialized_start=474
  _SENDHEARTBEATRESP._serialized_end=536
  _GETALLACTIVESCENESRESP._serialized_start=538
  _GETALLACTIVESCENESRESP._serialized_end=634
# @@protoc_insertion_point(module_scope)
