# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcam_remote_vehicle_immobilization.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(tcam_remote_vehicle_immobilization.proto\"=\n\rRviRequestHpa\x12,\n\x10rvi_request_type\x18\x01 \x01(\x0e\x32\x12.RviRequestTypeHpa\"D\n\x0eRviResponseHpa\x12\x32\n\x13rvi_response_status\x18\x01 \x01(\x0e\x32\x15.RviResponseStatusHpa\"\x15\n\x13RviStatusRequestHpa\"7\n\x12RviStatusUpdateHpa\x12!\n\nrvi_status\x18\x01 \x01(\x0e\x32\r.RviStatusHpa*f\n\x11RviRequestTypeHpa\x12\x1b\n\x17RVI_REQUEST_UNSPECIFIED\x10\x00\x12\x1a\n\x16RVI_REQUEST_IMMOBILIZE\x10\x01\x12\x18\n\x14RVI_REQUEST_MOBILIZE\x10\x02*{\n\x14RviResponseStatusHpa\x12#\n\x1fRVI_RESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bRVI_RESPONSE_STATUS_SUCCESS\x10\x01\x12\x1d\n\x19RVI_RESPONSE_STATUS_ERROR\x10\x02*\x94\x01\n\x0cRviStatusHpa\x12\x1a\n\x16RVI_STATUS_UNSPECIFIED\x10\x00\x12\x13\n\x0fRVI_STATUS_IDLE\x10\x01\x12\x1a\n\x16RVI_STATUS_IMMOBILIZED\x10\x02\x12\x18\n\x14RVI_STATUS_MOBILIZED\x10\x03\x12\x1d\n\x19RVI_STATUS_START_DISABLED\x10\x04\x62\x06proto3')

_RVIREQUESTTYPEHPA = DESCRIPTOR.enum_types_by_name['RviRequestTypeHpa']
RviRequestTypeHpa = enum_type_wrapper.EnumTypeWrapper(_RVIREQUESTTYPEHPA)
_RVIRESPONSESTATUSHPA = DESCRIPTOR.enum_types_by_name['RviResponseStatusHpa']
RviResponseStatusHpa = enum_type_wrapper.EnumTypeWrapper(_RVIRESPONSESTATUSHPA)
_RVISTATUSHPA = DESCRIPTOR.enum_types_by_name['RviStatusHpa']
RviStatusHpa = enum_type_wrapper.EnumTypeWrapper(_RVISTATUSHPA)
RVI_REQUEST_UNSPECIFIED = 0
RVI_REQUEST_IMMOBILIZE = 1
RVI_REQUEST_MOBILIZE = 2
RVI_RESPONSE_STATUS_UNSPECIFIED = 0
RVI_RESPONSE_STATUS_SUCCESS = 1
RVI_RESPONSE_STATUS_ERROR = 2
RVI_STATUS_UNSPECIFIED = 0
RVI_STATUS_IDLE = 1
RVI_STATUS_IMMOBILIZED = 2
RVI_STATUS_MOBILIZED = 3
RVI_STATUS_START_DISABLED = 4


_RVIREQUESTHPA = DESCRIPTOR.message_types_by_name['RviRequestHpa']
_RVIRESPONSEHPA = DESCRIPTOR.message_types_by_name['RviResponseHpa']
_RVISTATUSREQUESTHPA = DESCRIPTOR.message_types_by_name['RviStatusRequestHpa']
_RVISTATUSUPDATEHPA = DESCRIPTOR.message_types_by_name['RviStatusUpdateHpa']
RviRequestHpa = _reflection.GeneratedProtocolMessageType('RviRequestHpa', (_message.Message,), {
  'DESCRIPTOR' : _RVIREQUESTHPA,
  '__module__' : 'tcam_remote_vehicle_immobilization_pb2'
  # @@protoc_insertion_point(class_scope:RviRequestHpa)
  })
_sym_db.RegisterMessage(RviRequestHpa)

RviResponseHpa = _reflection.GeneratedProtocolMessageType('RviResponseHpa', (_message.Message,), {
  'DESCRIPTOR' : _RVIRESPONSEHPA,
  '__module__' : 'tcam_remote_vehicle_immobilization_pb2'
  # @@protoc_insertion_point(class_scope:RviResponseHpa)
  })
_sym_db.RegisterMessage(RviResponseHpa)

RviStatusRequestHpa = _reflection.GeneratedProtocolMessageType('RviStatusRequestHpa', (_message.Message,), {
  'DESCRIPTOR' : _RVISTATUSREQUESTHPA,
  '__module__' : 'tcam_remote_vehicle_immobilization_pb2'
  # @@protoc_insertion_point(class_scope:RviStatusRequestHpa)
  })
_sym_db.RegisterMessage(RviStatusRequestHpa)

RviStatusUpdateHpa = _reflection.GeneratedProtocolMessageType('RviStatusUpdateHpa', (_message.Message,), {
  'DESCRIPTOR' : _RVISTATUSUPDATEHPA,
  '__module__' : 'tcam_remote_vehicle_immobilization_pb2'
  # @@protoc_insertion_point(class_scope:RviStatusUpdateHpa)
  })
_sym_db.RegisterMessage(RviStatusUpdateHpa)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RVIREQUESTTYPEHPA._serialized_start=257
  _RVIREQUESTTYPEHPA._serialized_end=359
  _RVIRESPONSESTATUSHPA._serialized_start=361
  _RVIRESPONSESTATUSHPA._serialized_end=484
  _RVISTATUSHPA._serialized_start=487
  _RVISTATUSHPA._serialized_end=635
  _RVIREQUESTHPA._serialized_start=44
  _RVIREQUESTHPA._serialized_end=105
  _RVIRESPONSEHPA._serialized_start=107
  _RVIRESPONSEHPA._serialized_end=175
  _RVISTATUSREQUESTHPA._serialized_start=177
  _RVISTATUSREQUESTHPA._serialized_end=198
  _RVISTATUSUPDATEHPA._serialized_start=200
  _RVISTATUSUPDATEHPA._serialized_end=255
# @@protoc_insertion_point(module_scope)
