# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcam_honk_car_locator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btcam_honk_car_locator.proto\x1a\x0cnanopb.proto\"\x1a\n\x18HonkCarLocatorRequestHpa\",\n\x19HonkCarLocatorResponseHpa\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')



_HONKCARLOCATORREQUESTHPA = DESCRIPTOR.message_types_by_name['HonkCarLocatorRequestHpa']
_HONKCARLOCATORRESPONSEHPA = DESCRIPTOR.message_types_by_name['HonkCarLocatorResponseHpa']
HonkCarLocatorRequestHpa = _reflection.GeneratedProtocolMessageType('HonkCarLocatorRequestHpa', (_message.Message,), {
  'DESCRIPTOR' : _HONKCARLOCATORREQUESTHPA,
  '__module__' : 'tcam_honk_car_locator_pb2'
  # @@protoc_insertion_point(class_scope:HonkCarLocatorRequestHpa)
  })
_sym_db.RegisterMessage(HonkCarLocatorRequestHpa)

HonkCarLocatorResponseHpa = _reflection.GeneratedProtocolMessageType('HonkCarLocatorResponseHpa', (_message.Message,), {
  'DESCRIPTOR' : _HONKCARLOCATORRESPONSEHPA,
  '__module__' : 'tcam_honk_car_locator_pb2'
  # @@protoc_insertion_point(class_scope:HonkCarLocatorResponseHpa)
  })
_sym_db.RegisterMessage(HonkCarLocatorResponseHpa)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HONKCARLOCATORREQUESTHPA._serialized_start=45
  _HONKCARLOCATORREQUESTHPA._serialized_end=71
  _HONKCARLOCATORRESPONSEHPA._serialized_start=73
  _HONKCARLOCATORRESPONSEHPA._serialized_end=117
# @@protoc_insertion_point(module_scope)
