# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tcam_cloud_services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import signals_base_pb2 as signals__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tcam_cloud_services.proto\x1a\x12signals_base.proto\"K\n\x1e\x43loudServicesHPAWakeUpResponse\x12)\n\x0fresponse_status\x18\x01 \x01(\x0e\x32\x10.base.EErrorCode\"\xea\x03\n\x1d\x43loudServicesHPAWakeUpRequest\x12\x35\n\x06reason\x18\x01 \x01(\x0e\x32%.CloudServicesHPAWakeUpRequest.Reason\x12\x1b\n\x13keep_awake_duration\x18\x02 \x01(\r\x12\x39\n\x08resource\x18\x03 \x03(\x0e\x32\'.CloudServicesHPAWakeUpRequest.Resource\"\xde\x01\n\x06Reason\x12\x14\n\x10REASON_UNDEFINED\x10\x00\x12\x1e\n\x1aREASON_INFOTAINMENT_SYSTEM\x10\x01\x12\x1e\n\x1aREASON_CHARGING_SCENARIO_0\x10\x02\x12\x1e\n\x1aREASON_CHARGING_SCENARIO_1\x10\x03\x12\x1e\n\x1aREASON_CHARGING_SCENARIO_2\x10\x04\x12\x1e\n\x1aREASON_CHARGING_SCENARIO_3\x10\x05\x12\x1e\n\x1aREASON_CHARGING_SCENARIO_4\x10\x06\"Y\n\x08Resource\x12\x18\n\x14RESOURCE_UNSPECIFIED\x10\x00\x12\x19\n\x15RESOURCE_INFOTAINMENT\x10\x01\x12\x18\n\x14RESOURCE_CORE_SYSTEM\x10\x02\x62\x06proto3')



_CLOUDSERVICESHPAWAKEUPRESPONSE = DESCRIPTOR.message_types_by_name['CloudServicesHPAWakeUpResponse']
_CLOUDSERVICESHPAWAKEUPREQUEST = DESCRIPTOR.message_types_by_name['CloudServicesHPAWakeUpRequest']
_CLOUDSERVICESHPAWAKEUPREQUEST_REASON = _CLOUDSERVICESHPAWAKEUPREQUEST.enum_types_by_name['Reason']
_CLOUDSERVICESHPAWAKEUPREQUEST_RESOURCE = _CLOUDSERVICESHPAWAKEUPREQUEST.enum_types_by_name['Resource']
CloudServicesHPAWakeUpResponse = _reflection.GeneratedProtocolMessageType('CloudServicesHPAWakeUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDSERVICESHPAWAKEUPRESPONSE,
  '__module__' : 'tcam_cloud_services_pb2'
  # @@protoc_insertion_point(class_scope:CloudServicesHPAWakeUpResponse)
  })
_sym_db.RegisterMessage(CloudServicesHPAWakeUpResponse)

CloudServicesHPAWakeUpRequest = _reflection.GeneratedProtocolMessageType('CloudServicesHPAWakeUpRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDSERVICESHPAWAKEUPREQUEST,
  '__module__' : 'tcam_cloud_services_pb2'
  # @@protoc_insertion_point(class_scope:CloudServicesHPAWakeUpRequest)
  })
_sym_db.RegisterMessage(CloudServicesHPAWakeUpRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLOUDSERVICESHPAWAKEUPRESPONSE._serialized_start=49
  _CLOUDSERVICESHPAWAKEUPRESPONSE._serialized_end=124
  _CLOUDSERVICESHPAWAKEUPREQUEST._serialized_start=127
  _CLOUDSERVICESHPAWAKEUPREQUEST._serialized_end=617
  _CLOUDSERVICESHPAWAKEUPREQUEST_REASON._serialized_start=304
  _CLOUDSERVICESHPAWAKEUPREQUEST_REASON._serialized_end=526
  _CLOUDSERVICESHPAWAKEUPREQUEST_RESOURCE._serialized_start=528
  _CLOUDSERVICESHPAWAKEUPREQUEST_RESOURCE._serialized_end=617
# @@protoc_insertion_point(module_scope)
